### ISSUE TITLE
User guide file is not awailable.

### ISSUE THREAD

**Issue by khoroshyy** [biomadeira/pycoevol#1]
Hi. 
I have tried to download user manual, but lint to it is broken.

**Comment by biomadeira** [comment]
I just added the "Pycoevol_userguide". Sorry about the link and any mistakes that you may find in the code/user guide. 

Anything else, just drop a line! 

Cheers

**Comment by biomadeira** [comment]
Also, you may find https://github.com/fmadeira/pycma interesting but it is even more experimental than Pycoevol...
